### ISSUE TITLE
Lost Ark watcher  not found file error, log included.

### ISSUE THREAD

**Issue by cybx** [Lost-Ark-Market-Online/LostArk-Market-Watcher#5]
Hey, i did download the last version of watcher, and when i tried to open, he asks for the email and password, after that, he ask for download the new launcher, and i accepted, after that, the watcher cant open the launcher.

I modify the config file to log de errors, here what is on the log file:

2022-09-17T11:22:12 - WATCHER - ERROR - [WinError 2] O sistema não pode encontrar o arquivo especificado.
Traceback (most recent call last):
  File "C:\Users\Victor\AppData\Local\Temp\ONDC6E~1\index.py", line 178, in <module>
  File "C:\Users\Victor\AppData\Local\Temp\ONDC6E~1\index.py", line 58, in __init__
  File "C:\Users\Victor\AppData\Local\Temp\ONDC6E~1\index.py", line 115, in spawn_observer
  File "C:\Users\Victor\AppData\Local\Temp\ONDC6E~1\watchdog\observers\api.py", line 262, in start
  File "C:\Users\Victor\AppData\Local\Temp\ONDC6E~1\watchdog\utils\__init__.py", line 93, in start
  File "C:\Users\Victor\AppData\Local\Temp\ONDC6E~1\watchdog\observers\read_directory_changes.py", line 67, in on_thread_start
  File "C:\Users\Victor\AppData\Local\Temp\ONDC6E~1\watchdog\observers\winapi.py", line 316, in get_directory_handle
  File "C:\Users\Victor\AppData\Local\Temp\ONDC6E~1\watchdog\observers\winapi.py", line 112, in _errcheck_handle
FileNotFoundError: [WinError 2] O sistema não pode encontrar o arquivo especificado.

*Portuguese to english translate of the last and first line:
*FileNotFoundError: [WinError 2] O sistema não pode encontrar o arquivo especificado.
*FileNotFoundError: [WinError 2] The system cannot found the file specified

**Comment by gogodr** [comment]
The problem is the app not finding the screenshot folder when trying to spawn the observer.
This can happen if you have a fresh install of the game and the screenshot folder has not been generated yet. (To fix it, just go ingame and take a screenshot)
Or if the game path was not configured correctly.
I will add a safety measure in a future commit to check the file configured and automatically create the folder if the path is correct but missing the screenshot folder.
